# Generated by Django 4.1.7 on 2023-03-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_tecnology_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='sobrenome')),
                ('ddd', models.IntegerField(verbose_name='ddd')),
                ('telephone', models.IntegerField(verbose_name='telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('about', models.TextField(verbose_name='sobre mim')),
                ('about_dev', models.TextField(verbose_name='sobre carreira')),
                ('stacks', models.ManyToManyField(to='projects.tecnology')),
            ],
        ),
    ]
