# Generated by Django 4.1.7 on 2023-03-04 23:52

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='tec name')),
                ('use', models.IntegerField(choices=[(0, 'back-end'), (1, 'front-end'), (2, 'ops'), (3, 'database')], verbose_name='tecnology usage')),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='repo name')),
                ('description', models.TextField(max_length=500)),
                ('link', models.URLField(blank=True, null=True, verbose_name='link project')),
                ('photo_os', models.ImageField(upload_to=projects.models.project_directory_path)),
                ('data', models.DateField()),
                ('last_update', models.DateField(auto_now=True)),
                ('tecnologies', models.ManyToManyField(to='projects.tecnology')),
            ],
        ),
    ]
