# Generated by Django 4.1.7 on 2023-03-05 00:10

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo_os',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.project_directory_path),
        ),
    ]
