# Generated by Django 4.1.7 on 2023-03-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_photo_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnology',
            name='use',
            field=models.IntegerField(choices=[(0, 'back-end'), (1, 'front-end'), (2, 'ops'), (3, 'database'), (4, 'lib')], verbose_name='tecnology usage'),
        ),
    ]
