# Generated by Django 4.1.7 on 2023-03-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('ddd', models.IntegerField(verbose_name='ddd')),
                ('telephone', models.IntegerField(verbose_name='telefone')),
                ('subject', models.CharField(max_length=150, verbose_name='assunto')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
